# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cloudterminal < Formula
  desc "Terminal multiplexer for Claude Code sessions"
  homepage "https://github.com/tmyktmyc/BlinkingLine-cloudterminal"
  version "0.4.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tmyktmyc/BlinkingLine-cloudterminal/releases/download/v0.4.0/cloudterminal_0.4.0_darwin_amd64.tar.gz"
      sha256 "cf5bccf76d0dbd36c502fa3057f853292afaaa218f600ede97e6bcd8e7cc43f4"

      define_method(:install) do
        bin.install "cloudterminal"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tmyktmyc/BlinkingLine-cloudterminal/releases/download/v0.4.0/cloudterminal_0.4.0_darwin_arm64.tar.gz"
      sha256 "081620d3a2eb5cc06a5140cbabf3b470a861e53c0ca9fcb9fa0bf3c33ca45bab"

      define_method(:install) do
        bin.install "cloudterminal"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tmyktmyc/BlinkingLine-cloudterminal/releases/download/v0.4.0/cloudterminal_0.4.0_linux_amd64.tar.gz"
      sha256 "0b73ed015cb3ea66e203e59991de9e927c6253aee7d67efc46dfdb471cc5205f"
      define_method(:install) do
        bin.install "cloudterminal"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tmyktmyc/BlinkingLine-cloudterminal/releases/download/v0.4.0/cloudterminal_0.4.0_linux_arm64.tar.gz"
      sha256 "f6e3ee82714847a78291faf72332ad5c35aeaff48b42e97432b4028d3efa69c6"
      define_method(:install) do
        bin.install "cloudterminal"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/cloudterminal --version")
  end
end
