# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cloudterminal < Formula
  desc "Terminal multiplexer for Claude Code sessions"
  homepage "https://github.com/tmyktmyc/BlinkingLine-cloudterminal"
  version "0.3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tmyktmyc/BlinkingLine-cloudterminal/releases/download/v0.3.0/cloudterminal_0.3.0_darwin_amd64.tar.gz"
      sha256 "462c3a54621f0a2e6af7a5e3aea39b77f4001fc152502cc2e5f7279b3b600291"

      define_method(:install) do
        bin.install "cloudterminal"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tmyktmyc/BlinkingLine-cloudterminal/releases/download/v0.3.0/cloudterminal_0.3.0_darwin_arm64.tar.gz"
      sha256 "f1f661bb8e98123ea814ec1a4427763970b1525850e8d7908baf9aaa19a798e9"

      define_method(:install) do
        bin.install "cloudterminal"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tmyktmyc/BlinkingLine-cloudterminal/releases/download/v0.3.0/cloudterminal_0.3.0_linux_amd64.tar.gz"
      sha256 "b93da44a9b521023ac9ceb15bf1286e4c59dd7594c497df642f28e957d0f0da2"
      define_method(:install) do
        bin.install "cloudterminal"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tmyktmyc/BlinkingLine-cloudterminal/releases/download/v0.3.0/cloudterminal_0.3.0_linux_arm64.tar.gz"
      sha256 "88ef344d72033e369926df34f9f94f561ffc48d7970e8712d619bda19c8ded55"
      define_method(:install) do
        bin.install "cloudterminal"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/cloudterminal --version")
  end
end
